### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by xuwenchao66** [xuwenchao66/mono-packages#1]
- [ ] 使用 https://www.npmjs.com/package/inquirer 实现&简化 dev、build package 按需执行操作。
- [ ] production build 模式 & npm scripts，直接 build 所有 package。
- [ ] 通用 plugins、external 等配置。
- [ ] 通用 test。
- [ ] vue 组件 package 的通用构建、配置。
